### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by svddries** [tue-robotics/ed_rviz_plugins#1]
rviz_plugins/CMakeFiles/rviz_plugins.dir/depend.make:4: **\* target pattern contains no `%'.  Stop.

**Comment by reinzor** [comment]
amigo@dct68 $ tue-make-dev
Base path: /home/amigo/ros/hydro/dev
Source space: /home/amigo/ros/hydro/dev/src
Build space: /home/amigo/ros/hydro/dev/build
Devel space: /home/amigo/ros/hydro/dev/devel
Install space: /home/amigo/ros/hydro/dev/install
####

#### Running command: "cmake /home/amigo/ros/hydro/dev/src -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCATKIN_DEVEL_PREFIX=/home/amigo/ros/hydro/dev/devel -DCMAKE_INSTALL_PREFIX=/home/amigo/ros/hydro/dev/install" in "/home/amigo/ros/hydro/dev/build"

####
-- The C compiler identification is GNU
-- The CXX compiler identification is GNU
-- Check for working C compiler: /usr/lib/ccache/gcc
-- Check for working C compiler: /usr/lib/ccache/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/lib/ccache/c++
-- Check for working CXX compiler: /usr/lib/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Using CATKIN_DEVEL_PREFIX: /home/amigo/ros/hydro/dev/devel
-- Using CMAKE_PREFIX_PATH: /home/amigo/ros/hydro/cmake;/home/amigo/ros/hydro/cmake;/home/amigo/ros/hydro/dev/devel;/home/amigo/ros/hydro/system/devel;/opt/ros/hydro
-- This workspace overlays: /home/amigo/ros/hydro/dev/devel;/home/amigo/ros/hydro/system/devel;/opt/ros/hydro
-- Found PythonInterp: /usr/bin/python (found version "2.7.3")
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Python version: 2.7
-- Using Debian Python package layout
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/amigo/ros/hydro/dev/build/test_results
-- Looking for include files CMAKE_HAVE_PTHREAD_H
-- Looking for include files CMAKE_HAVE_PTHREAD_H - found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE 
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- catkin 0.5.90
-- BUILD_SHARED_LIBS is on
WARNING: Package "ompl" does not follow the version conventions. It should not contain leading zeros (unless the number is 0).
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 1 packages in topological order:
-- ~~  - rviz_plugins
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'rviz_plugins'
-- ==> add_subdirectory(rviz_plugins)
-- Using these message generators: gencpp;genlisp;genpy
-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found.
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found.
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - not found.
-- Found Qt4: /usr/bin/qmake (found version "4.8.1")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/amigo/ros/hydro/dev/build
####

#### Running command: "make -j2 -l2" in "/home/amigo/ros/hydro/dev/build"

####
[ 25%] Generating src/displays/moc_world_model_display.cxx
Scanning dependencies of target rviz_plugins
[ 50%] [ 75%] Building CXX object rviz_plugins/CMakeFiles/rviz_plugins.dir/src/displays/world_model_display.cpp.o
Building CXX object rviz_plugins/CMakeFiles/rviz_plugins.dir/src/visuals/entity_visual.cpp.o
[100%] Building CXX object rviz_plugins/CMakeFiles/rviz_plugins.dir/src/displays/moc_world_model_display.cxx.o
Linking CXX shared library /home/amigo/ros/hydro/dev/devel/lib/librviz_plugins.so
[100%] Built target rviz_plugins

**Comment by reinzor** [comment]
This is due to the symbolic links :/

**Comment by Rayman** [comment]
This package still doesn't compile. Why was it added as dependency?

**Comment by reinzor** [comment]
It substitutes the rviz publisher of ed. Why does it not compile?

-Rein

**Comment by reinzor** [comment]
Compiles now; @Rayman , can you add travis build?
